# Generated by Django 5.2 on 2026-05-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='accesorios',
            field=models.ManyToManyField(blank=True, to='catalogo.accesorio'),
        ),
    ]
